name: build

on:
  push:
    branches: [ main ]

jobs:
  gcc-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - name: boost
        run: sudo apt-get update && sudo apt-get install -yq libboost-dev
      - name: build-tests
        run: |
          mkdir build && cd build
          cmake .. && make -j2 signals_test
      - name: run-tests
        run: ./build/tests/signals_test
  clang-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - name: boost
        run: sudo apt-get update && sudo apt-get install -yq libboost-dev
      - name: build-tests
        run: |
          mkdir build && cd build
          export CXX=clang++ && export CC=clang
          cmake .. && make -j2 signals_test
      - name: run-tests
        run: ./build/tests/signals_test
